services:
  my-postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=django-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe123
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d django-postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  my-mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pqwe123"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  my-django:
    build: .
    container_name: django
    ports:
      - 8000:8000
    depends_on:
      my-mysql:
        condition: service_healthy
      my-postgres:
        condition: service_healthy