name: docker-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: EC2 ssh connection and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # 연결할 EC2 
          username: ${{ secrets.SSH_USERNAME }}	 # 사용자
          key: ${{ secrets.SSH_KEY }}  # pem 파일 내용
          command_timeout: 5m	 #timeout 시간 설정
          script: |
            mkdir test